# Use the latest 2.1 version of CircleCI pipeline processing engine, see https://circleci.com/docs/2.0/configuration-reference/
version: 2.1

# Use a package of configuration called an orb, see https://circleci.com/docs/2.0/orb-intro/
orbs:
  gradle: circleci/gradle@1.0.11

executors:
  my-executor:
    docker:
      - image: 'circleci/openjdk:11'

commands:
  my-command:
    steps:
      - run: echo "lol"

jobs:
  my-job:
    executor: my-executor
    steps:
      - my-command

workflows:
  run_test:
    jobs:
      - gradle/test:
          executor: my-executor
          test_command: test
          test_results_path: ago/build/test-results/test
          reports_path: ago/build/reports/

      - gradle/run:
          executor: my-executor
          command: jar -x test
          requires:
            - gradle/test
