# Orb 'circleci/gradle@1.0.11' resolved to 'circleci/gradle@1.0.11'
version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk-node
    steps:
      - checkout
      - run:
          name: Generate Cache Checksum
          command: find . -name 'build.gradle' | sort | xargs cat | shasum | awk '{print
            $1}' > /tmp/gradle_cache_seed
      - restore_cache:
          key: gradle-{{ checksum "/tmp/gradle_cache_seed" }}-{{ checksum ".circleci/config.yml"
            }}
      - run:
          name: Run Tests
          command: ./gradlew test
      - save_cache:
          paths:
            - ~/.gradle/caches
            - ~/.gradle/wrapper
          key: gradle-{{ checksum "/tmp/gradle_cache_seed" }}-{{ checksum ".circleci/config.yml"
            }}
      - run:
          name: pwd
          command: pwd
      - run:
          name: ls
          command: ls
      - store_test_results:
          path: ago/build/test-results/test
      - store_artifacts:
          path: ago/build/reports
          destination: reports

    environment:
      - TERM: dumb

  gradle/test:
    docker:
      - image: circleci/openjdk:8-jdk-node
    steps:
      - checkout
      - run:
          name: Generate Cache Checksum
          command: find . -name 'build.gradle' | sort | xargs cat | shasum | awk '{print
            $1}' > /tmp/gradle_cache_seed
      - restore_cache:
          key: gradle-{{ checksum "/tmp/gradle_cache_seed" }}-{{ checksum ".circleci/config.yml"
            }}
      - run:
          name: Run Tests
          command: ./gradlew test
      - save_cache:
          paths:
            - ~/.gradle/caches
            - ~/.gradle/wrapper
          key: gradle-{{ checksum "/tmp/gradle_cache_seed" }}-{{ checksum ".circleci/config.yml"
            }}
      - store_test_results:
          path: ago/build/test-results/test
      - store_artifacts:
          path: ago/build/test-results/test
          destination: Results
      - store_artifacts:
          path: ago/build/reports
          destination: Reports
    environment:
      - TERM: dumb

workflows:
  build:
  #jobs:
  #  - gradle/test
  version: 2