version: 2.1

orbs:
  gradle: circleci/gradle@1.0.11

workflows:
  run_test:
    jobs:
      - gradle/test:
          test_command: test
          test_results_path: ago/build/test-results/test
          reports_path: ago/build/reports/

      - gradle/run:
          command: jar -x test
          requires:
            - gradle/test

      - gradle/run:
          command: :ago:publishToMavenLocal
          requires:
            - gradle/run