# Orb 'circleci/welcome-orb@0.3.1' resolved to 'circleci/welcome-orb@0.3.1'
# Orb 'circleci/gradle@1.0.11' resolved to 'circleci/gradle@1.0.11'
version: 2
jobs:
  build:
    machine:
      image: 'circleci/openjdk:8-jdk-node'
    steps:
      - checkout
      - run:
          name: Generate Cache Checksum
          command: find . -name 'build.gradle' | sort | xargs cat | shasum | awk '{print
            $1}' > /tmp/gradle_cache_seed
      - restore_cache:
          key: gradle-{{ checksum "/tmp/gradle_cache_seed" }}-{{ checksum ".circleci/config.yml"
            }}
      - run:
          name: Run Tests
          command: ./gradlew test
      - save_cache:
          paths:
            - ~/.gradle/caches
            - ~/.gradle/wrapper
          key: gradle-{{ checksum "/tmp/gradle_cache_seed" }}-{{ checksum ".circleci/config.yml"
            }}
      - run:
          name: pwd
          command: pwd
      - run:
          name: ls
          command: ls
      - store_test_results:
          path: ago/build/test-results/test
      - store_artifacts:
          path: ago/build/reports
          destination: reports

    environment:
      - TERM: dumb


  welcome/run:
    docker:
      - image: circleci/welcome-config-image:0.1.40-b28e6fe
    steps:
      - run:
          command: welcome_message.sh
          name: Welcome and basics to get you started
      - run:
          command: common_env_vars.sh
          name: Built-in environment variables for your project
      - run:
          command: next_steps.sh
          name: Next steps to customize your pipeline
  gradle/test:
    docker:
      - image: circleci/openjdk:8-jdk-node
    steps:
      - checkout
      - run:
          name: Generate Cache Checksum
          command: find . -name 'build.gradle' | sort | xargs cat | shasum | awk '{print
            $1}' > /tmp/gradle_cache_seed
      - restore_cache:
          key: gradle-{{ checksum "/tmp/gradle_cache_seed" }}-{{ checksum ".circleci/config.yml"
            }}
      - run:
          name: Run Tests
          command: ./gradlew test
      - save_cache:
          paths:
            - ~/.gradle/caches
            - ~/.gradle/wrapper
          key: gradle-{{ checksum "/tmp/gradle_cache_seed" }}-{{ checksum ".circleci/config.yml"
            }}
      - store_test_results:
          path: ago/build/test-results/test
      - store_artifacts:
          path: ago/build/test-results/test
          destination: Results
      - store_artifacts:
          path: ago/build/reports
          destination: Reports
    environment:
      - TERM: dumb
workflows:
  Welcome:
    jobs:
      - welcome/run
  build:
    jobs:
      - gradle/test
  version: 2

# Original config.yml file:
# # Use the latest 2.1 version of CircleCI pipeline processing engine, see https://circleci.com/docs/2.0/configuration-reference/
# version: 2.1
#
# # Use a package of configuration called an orb, see https://circleci.com/docs/2.0/orb-intro/
# orbs:
#   # Declare a dependency on the welcome-orb
#   welcome: circleci/welcome-orb@0.3.1
#   gradle: circleci/gradle@1.0.11
#
# executors:
#   my-executor:
#     docker:
#       - image: 'circleci/openjdk:11'
#
# # Orchestrate or schedule a set of jobs, see https://circleci.com/docs/2.0/workflows/
# workflows:
#   Welcome:
#     jobs:
#       - welcome/run
#
#   build:
#     jobs:
#     - gradle/test:
#         test_command: myTests
#         test_results_path: build/my-results/
#         reports_path: build/reports/